env:
  node: true
  commonjs: true
  es2021: true
extends:
  - airbnb-base
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
rules:
  consistent-return: off
  no-unused-vars: off
  no-console: off
  no-else-return: off
  prefer-destructuring: off
