env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
overrides: []
parserOptions:
  ecmaVersion: latest
plugins:
  - react
rules:
  react/prop-types: off
  react/react-in-jsx-scope: off
  react/jsx-filename-extension: off
  no-alert: off
  object-curly-newline: off
  no-confusing-arrow: off
  implicit-arrow-linebreak: off
  function-paren-newline: off
  no-unused-vars: off
  react/jsx-one-expression-per-line: off
  no-shadow: off
  jsx-quotes: [error, prefer-single]
  no-underscore-dangle: off
